# cfw run port
port: 6680
# Program running frequency, unit: second
frequency: 5
# Maximum number of connections running
max_num: 100
# time to unblock ip
unblock_time: 600
# Data backup time
backup_time: 60

# ipv4 whitelist
whitelist: /etc/cfw/ip_list/whitelist.txt
# ipv4 blacklist
blacklist: /etc/cfw/ip_list/blacklist.txt

# ipv6 whitelist
whitelist6: /etc/cfw/ip_list/whitelist6.txt
# ipv6 blacklist
blacklist6: /etc/cfw/ip_list/blacklist6.txt

# log file path
log_file_path: /etc/cfw/log/log.csv
log_max_lines: 10000000
